// POI category group definitions with labels, icons, and per-category colors

export interface POICategoryConfig {
  key:    string
  label:  string
  color:  string
  stroke: string
}

export interface POIGroupConfig {
  key:        string
  label:      string
  icon:       string // Lucide icon name
  categories: POICategoryConfig[]
}

export const POI_GROUPS: POIGroupConfig[] = [
  {
    key: 'heritage', label: 'Heritage', icon: 'Castle',
    categories: [
      { key: 'castle',              label: 'Castles',              color: '#854d0e', stroke: '#713f12' },
      { key: 'palace',              label: 'Palaces',              color: '#a16207', stroke: '#854d0e' },
      { key: 'manor',               label: 'Manors',               color: '#b45309', stroke: '#92400e' },
      { key: 'historic_house',      label: 'Historic Houses',      color: '#c2410c', stroke: '#9a3412' },
      { key: 'ruins',               label: 'Ruins',                color: '#78716c', stroke: '#57534e' },
      { key: 'archaeological_site', label: 'Archaeological',       color: '#92400e', stroke: '#78350f' },
      { key: 'city_gate',           label: 'City Gates',           color: '#a16207', stroke: '#854d0e' },
      { key: 'bunker',              label: 'Bunkers',              color: '#525252', stroke: '#404040' },
      { key: 'berlin_wall',         label: 'Berlin Wall',          color: '#475569', stroke: '#334155' },
      { key: 'windmill',            label: 'Windmills',            color: '#65a30d', stroke: '#4d7c0f' },
      { key: 'stolperstein',        label: 'Stolpersteine',        color: '#d4a017', stroke: '#b8860b' },
      { key: 'historic_cemetery',   label: 'Historic Cemeteries',  color: '#78716c', stroke: '#57534e' },
      { key: 'industrial_heritage', label: 'Industrial Heritage',  color: '#92400e', stroke: '#78350f' },
      { key: 'tomb',               label: 'Tombs',              color: '#525252', stroke: '#404040' },
      { key: 'boundary_stone',     label: 'Boundary Stones',    color: '#78716c', stroke: '#57534e' },
      { key: 'wayside_shrine',     label: 'Wayside Shrines',    color: '#a16207', stroke: '#854d0e' },
      { key: 'milestone_historic', label: 'Milestones',         color: '#78716c', stroke: '#57534e' },
      { key: 'locomotive',         label: 'Historic Trains',    color: '#dc2626', stroke: '#b91c1c' },
      { key: 'lighthouse',         label: 'Lighthouses',        color: '#eab308', stroke: '#ca8a04' },
    ],
  },
  {
    key: 'monuments', label: 'Monuments', icon: 'Milestone',
    categories: [
      { key: 'monument',     label: 'Monuments',     color: '#b91c1c', stroke: '#991b1b' },
      { key: 'memorial',     label: 'Memorials',     color: '#9f1239', stroke: '#881337' },
      { key: 'war_memorial', label: 'War Memorials', color: '#6b7280', stroke: '#4b5563' },
      { key: 'statue',       label: 'Statues',       color: '#7c3aed', stroke: '#6d28d9' },
      { key: 'fountain',     label: 'Fountains',     color: '#0284c7', stroke: '#0369a1' },
      { key: 'artwork',      label: 'Public Art',    color: '#e879f9', stroke: '#d946ef' },
    ],
  },
  {
    key: 'worship', label: 'Worship', icon: 'Church',
    categories: [
      { key: 'church',    label: 'Churches',    color: '#a16207', stroke: '#854d0e' },
      { key: 'cathedral', label: 'Cathedrals',  color: '#854d0e', stroke: '#713f12' },
      { key: 'synagogue', label: 'Synagogues',  color: '#1d4ed8', stroke: '#1e40af' },
      { key: 'mosque',    label: 'Mosques',     color: '#059669', stroke: '#047857' },
      { key: 'chapel',    label: 'Chapels',     color: '#b45309', stroke: '#92400e' },
    ],
  },
  {
    key: 'tourism', label: 'Tourism', icon: 'Camera',
    categories: [
      { key: 'sight',              label: 'Sights',      color: '#dc2626', stroke: '#b91c1c' },
      { key: 'viewpoint',          label: 'Viewpoints',  color: '#16a34a', stroke: '#15803d' },
      { key: 'observation_tower',  label: 'Towers',      color: '#7c3aed', stroke: '#6d28d9' },
      { key: 'information',        label: 'Info Points', color: '#2563eb', stroke: '#1d4ed8' },
      { key: 'zoo',                label: 'Zoos',        color: '#ca8a04', stroke: '#a16207' },
      { key: 'aquarium',           label: 'Aquariums',   color: '#0891b2', stroke: '#0e7490' },
      { key: 'theme_park',         label: 'Theme Parks', color: '#e11d48', stroke: '#be123c' },
      { key: 'osm_museum',         label: 'Museums',     color: '#b45309', stroke: '#92400e' },
      { key: 'osm_gallery',        label: 'Galleries',   color: '#7c3aed', stroke: '#6d28d9' },
      { key: 'osm_cinema',         label: 'Cinemas',     color: '#0891b2', stroke: '#0e7490' },
    ],
  },
  {
    key: 'nature', label: 'Nature', icon: 'TreePine',
    categories: [
      { key: 'lake',            label: 'Lakes',     color: '#0284c7', stroke: '#0369a1' },
      { key: 'beach',           label: 'Beaches',   color: '#eab308', stroke: '#ca8a04' },
      { key: 'forest',          label: 'Forests',   color: '#15803d', stroke: '#166534' },
      { key: 'nature_reserve',  label: 'Reserves',  color: '#16a34a', stroke: '#15803d' },
      { key: 'garden',          label: 'Gardens',   color: '#65a30d', stroke: '#4d7c0f' },
      { key: 'cemetery_park',   label: 'Cemeteries',color: '#6b7280', stroke: '#4b5563' },
      { key: 'allotment_garden',label: 'Kleingarten',color:'#4d7c0f', stroke: '#365314' },
      { key: 'pond',            label: 'Ponds',     color: '#0284c7', stroke: '#0369a1' },
      { key: 'community_garden',label: 'Community Gardens', color: '#4d7c0f', stroke: '#365314' },
      { key: 'bathing_spot',    label: 'Bathing Spots',     color: '#0891b2', stroke: '#0e7490' },
      { key: 'picnic_site',     label: 'Picnic Sites',      color: '#65a30d', stroke: '#4d7c0f' },
      { key: 'waterfall',       label: 'Waterfalls',        color: '#0284c7', stroke: '#0369a1' },
      { key: 'spring',          label: 'Springs',           color: '#0891b2', stroke: '#0e7490' },
      { key: 'water_tower',     label: 'Water Towers',      color: '#0369a1', stroke: '#075985' },
      { key: 'pier',            label: 'Piers',             color: '#475569', stroke: '#334155' },
    ],
  },
  {
    key: 'transport', label: 'Transport', icon: 'Train',
    categories: [
      { key: 'sbahn',       label: 'S-Bahn',       color: '#16a34a', stroke: '#15803d' },
      { key: 'ubahn',       label: 'U-Bahn',       color: '#2563eb', stroke: '#1d4ed8' },
      { key: 'bike_rental', label: 'Bike Rental',  color: '#ea580c', stroke: '#c2410c' },
      { key: 'ev_charging', label: 'EV Charging',  color: '#0891b2', stroke: '#0e7490' },
      { key: 'ferry',       label: 'Ferries',      color: '#0369a1', stroke: '#075985' },
      { key: 'parking',     label: 'Parking',      color: '#6b7280', stroke: '#4b5563' },
      { key: 'tram_stop',   label: 'Tram Stops',   color: '#dc2626', stroke: '#b91c1c' },
      { key: 'car_sharing',     label: 'Car Sharing',    color: '#059669', stroke: '#047857' },
      { key: 'scooter_rental',  label: 'Scooter Rental', color: '#f59e0b', stroke: '#d97706' },
      { key: 'taxi',            label: 'Taxi Stands',    color: '#eab308', stroke: '#ca8a04' },
      { key: 'bus_stop',        label: 'Bus Stops',      color: '#dc2626', stroke: '#b91c1c' },
      { key: 'bicycle_parking', label: 'Bike Parking',   color: '#6b7280', stroke: '#4b5563' },
      { key: 'car_rental',     label: 'Car Rental',     color: '#7c3aed', stroke: '#6d28d9' },
      { key: 'airport',         label: 'Airports',       color: '#475569', stroke: '#334155' },
      { key: 'marina',          label: 'Marinas',        color: '#0369a1', stroke: '#075985' },
    ],
  },
  {
    key: 'food_drink', label: 'Food & Drink', icon: 'UtensilsCrossed',
    categories: [
      { key: 'restaurant',  label: 'Restaurants',  color: '#dc2626', stroke: '#b91c1c' },
      { key: 'cafe',        label: 'Cafes',        color: '#b45309', stroke: '#92400e' },
      { key: 'beer_garden', label: 'Beer Gardens', color: '#ca8a04', stroke: '#a16207' },
      { key: 'market',      label: 'Markets',      color: '#65a30d', stroke: '#4d7c0f' },
      { key: 'bakery',      label: 'Bakeries',     color: '#d97706', stroke: '#b45309' },
      { key: 'ice_cream',   label: 'Ice Cream',    color: '#ec4899', stroke: '#db2777' },
      { key: 'fast_food',   label: 'Fast Food',    color: '#ea580c', stroke: '#c2410c' },
      { key: 'food_court',  label: 'Food Courts',  color: '#d97706', stroke: '#b45309' },
      { key: 'brewery',     label: 'Breweries',    color: '#92400e', stroke: '#78350f' },
      { key: 'kebab',       label: 'Kebab',        color: '#ea580c', stroke: '#c2410c' },
      { key: 'vietnamese',  label: 'Vietnamese',   color: '#059669', stroke: '#047857' },
      { key: 'vegan',       label: 'Vegan',        color: '#16a34a', stroke: '#15803d' },
      { key: 'wochenmarkt', label: 'Weekly Markets',color: '#ca8a04', stroke: '#a16207' },
      { key: 'deli',        label: 'Delis',         color: '#b45309', stroke: '#92400e' },
      { key: 'butcher',     label: 'Butchers',      color: '#dc2626', stroke: '#b91c1c' },
      { key: 'pastry',      label: 'Pastry Shops',  color: '#d97706', stroke: '#b45309' },
      { key: 'tea_house',   label: 'Tea Houses',    color: '#15803d', stroke: '#166534' },
      { key: 'cheese_shop', label: 'Cheese Shops',  color: '#ca8a04', stroke: '#a16207' },
      { key: 'seafood',     label: 'Seafood',       color: '#0369a1', stroke: '#075985' },
    ],
  },
  {
    key: 'sports', label: 'Sports', icon: 'Dumbbell',
    categories: [
      { key: 'gym',            label: 'Gyms',           color: '#dc2626', stroke: '#b91c1c' },
      { key: 'pool',           label: 'Pools',          color: '#0284c7', stroke: '#0369a1' },
      { key: 'climbing',       label: 'Climbing',       color: '#ea580c', stroke: '#c2410c' },
      { key: 'sports_centre',  label: 'Sports Centres', color: '#16a34a', stroke: '#15803d' },
      { key: 'boat_rental',    label: 'Boat Rental',    color: '#0891b2', stroke: '#0e7490' },
      { key: 'stadium',        label: 'Stadiums',       color: '#7c3aed', stroke: '#6d28d9' },
      { key: 'playground',      label: 'Playgrounds',    color: '#f59e0b', stroke: '#d97706' },
      { key: 'skatepark',       label: 'Skateparks',     color: '#6366f1', stroke: '#4f46e5' },
      { key: 'dog_park',        label: 'Dog Parks',      color: '#65a30d', stroke: '#4d7c0f' },
      { key: 'table_tennis',    label: 'Table Tennis',   color: '#0891b2', stroke: '#0e7490' },
      { key: 'bowling',         label: 'Bowling',        color: '#7c3aed', stroke: '#6d28d9' },
      { key: 'escape_room',     label: 'Escape Rooms',   color: '#e11d48', stroke: '#be123c' },
      { key: 'mini_golf',       label: 'Mini Golf',      color: '#16a34a', stroke: '#15803d' },
      { key: 'outdoor_gym',     label: 'Outdoor Gyms',   color: '#ea580c', stroke: '#c2410c' },
      { key: 'yoga',             label: 'Yoga',           color: '#7c3aed', stroke: '#6d28d9' },
      { key: 'dance_studio',     label: 'Dance Studios',  color: '#e11d48', stroke: '#be123c' },
      { key: 'golf_course',      label: 'Golf Courses',   color: '#16a34a', stroke: '#15803d' },
      { key: 'horse_riding',     label: 'Horse Riding',   color: '#92400e', stroke: '#78350f' },
      { key: 'tennis',           label: 'Tennis',         color: '#16a34a', stroke: '#15803d' },
      { key: 'martial_arts',     label: 'Martial Arts',   color: '#dc2626', stroke: '#b91c1c' },
      { key: 'swimming_outdoor', label: 'Outdoor Swimming',color: '#0284c7', stroke: '#0369a1' },
    ],
  },
  {
    key: 'services', label: 'Services', icon: 'Building2',
    categories: [
      { key: 'pharmacy',      label: 'Pharmacies',    color: '#dc2626', stroke: '#b91c1c' },
      { key: 'post_office',   label: 'Post Offices',  color: '#eab308', stroke: '#ca8a04' },
      { key: 'hospital',      label: 'Hospitals',     color: '#e11d48', stroke: '#be123c' },
      { key: 'embassy',       label: 'Embassies',     color: '#1d4ed8', stroke: '#1e40af' },
      { key: 'public_toilet', label: 'Toilets',       color: '#6b7280', stroke: '#4b5563' },
      { key: 'library',       label: 'Libraries',     color: '#0369a1', stroke: '#075985' },
      { key: 'coworking',     label: 'Coworking',     color: '#7c3aed', stroke: '#6d28d9' },
      { key: 'dentist',      label: 'Dentists',      color: '#0891b2', stroke: '#0e7490' },
      { key: 'doctor',       label: 'Doctors',       color: '#0284c7', stroke: '#0369a1' },
      { key: 'police',       label: 'Police',        color: '#1d4ed8', stroke: '#1e40af' },
      { key: 'atm',          label: 'ATMs',          color: '#059669', stroke: '#047857' },
      { key: 'laundry',      label: 'Laundry',       color: '#6b7280', stroke: '#4b5563' },
      { key: 'veterinary',   label: 'Veterinary',    color: '#16a34a', stroke: '#15803d' },
      { key: 'recycling',    label: 'Recycling',     color: '#4d7c0f', stroke: '#365314' },
      { key: 'social_facility', label: 'Social Services', color: '#7c3aed', stroke: '#6d28d9' },
      { key: 'nette_toilette',  label: 'Nette Toilette',  color: '#059669', stroke: '#047857' },
      { key: 'optician',        label: 'Opticians',       color: '#6366f1', stroke: '#4f46e5' },
      { key: 'bank',            label: 'Banks',            color: '#ca8a04', stroke: '#a16207' },
      { key: 'fuel',            label: 'Gas Stations',     color: '#dc2626', stroke: '#b91c1c' },
      { key: 'car_wash',        label: 'Car Wash',         color: '#6b7280', stroke: '#4b5563' },
      { key: 'clinic',          label: 'Clinics',          color: '#e11d48', stroke: '#be123c' },
      { key: 'fire_station',    label: 'Fire Stations',    color: '#dc2626', stroke: '#b91c1c' },
      { key: 'townhall',        label: 'Town Halls',       color: '#1d4ed8', stroke: '#1e40af' },
      { key: 'hairdresser',     label: 'Hairdressers',     color: '#ec4899', stroke: '#db2777' },
      { key: 'beauty_salon',    label: 'Beauty Salons',    color: '#d946ef', stroke: '#a21caf' },
      { key: 'dry_cleaning',    label: 'Dry Cleaning',     color: '#6b7280', stroke: '#4b5563' },
      { key: 'travel_agency',   label: 'Travel Agencies',  color: '#0891b2', stroke: '#0e7490' },
      { key: 'estate_agent',    label: 'Estate Agents',    color: '#7c3aed', stroke: '#6d28d9' },
      { key: 'notary',          label: 'Notaries',         color: '#1d4ed8', stroke: '#1e40af' },
      { key: 'insurance',       label: 'Insurance',        color: '#2563eb', stroke: '#1d4ed8' },
      { key: 'lawyer',          label: 'Lawyers',          color: '#475569', stroke: '#334155' },
      { key: 'accountant',      label: 'Accountants',      color: '#059669', stroke: '#047857' },
      { key: 'funeral_home',    label: 'Funeral Homes',    color: '#525252', stroke: '#404040' },
      { key: 'animal_shelter',  label: 'Animal Shelters',  color: '#65a30d', stroke: '#4d7c0f' },
      { key: 'childcare',       label: 'Childcare',        color: '#f59e0b', stroke: '#d97706' },
      { key: 'internet_cafe',   label: 'Internet Cafés',   color: '#2563eb', stroke: '#1d4ed8' },
    ],
  },
  {
    key: 'nightlife', label: 'Nightlife', icon: 'Wine',
    categories: [
      { key: 'bar',           label: 'Bars',           color: '#dc2626', stroke: '#b91c1c' },
      { key: 'pub',           label: 'Pubs',           color: '#b45309', stroke: '#92400e' },
      { key: 'wine_bar',      label: 'Wine Bars',      color: '#9f1239', stroke: '#881337' },
      { key: 'hookah_lounge', label: 'Hookah Lounges', color: '#6b7280', stroke: '#4b5563' },
      { key: 'nightclub',     label: 'Clubs',          color: '#9333ea', stroke: '#7e22ce' },
      { key: 'cocktail_bar',  label: 'Cocktail Bars',  color: '#be123c', stroke: '#881337' },
      { key: 'live_music_poi',label: 'Live Music',     color: '#1d4ed8', stroke: '#1e3a8a' },
      { key: 'karaoke',       label: 'Karaoke',        color: '#d946ef', stroke: '#a21caf' },
      { key: 'rooftop_bar',  label: 'Rooftop Bars',   color: '#ea580c', stroke: '#c2410c' },
    ],
  },
  {
    key: 'shopping', label: 'Shopping', icon: 'ShoppingBag',
    categories: [
      { key: 'supermarket',  label: 'Supermarkets', color: '#16a34a', stroke: '#15803d' },
      { key: 'flea_market',  label: 'Flea Markets', color: '#d97706', stroke: '#b45309' },
      { key: 'mall',         label: 'Malls',        color: '#7c3aed', stroke: '#6d28d9' },
      { key: 'bookshop',     label: 'Bookshops',    color: '#0369a1', stroke: '#075985' },
      { key: 'record_shop',  label: 'Record Shops', color: '#7c3aed', stroke: '#4c1d95' },
      { key: 'vintage_shop', label: 'Vintage',      color: '#d97706', stroke: '#92400e' },
      { key: 'convenience',  label: 'Convenience',  color: '#059669', stroke: '#047857' },
      { key: 'florist',      label: 'Florists',     color: '#ec4899', stroke: '#db2777' },
      { key: 'bicycle_shop',  label: 'Bike Shops',    color: '#15803d', stroke: '#14532d' },
      { key: 'organic_shop',  label: 'Organic Shops', color: '#65a30d', stroke: '#4d7c0f' },
      { key: 'wine_shop',     label: 'Wine Shops',    color: '#9f1239', stroke: '#881337' },
      { key: 'charity_shop',  label: 'Charity Shops', color: '#0891b2', stroke: '#0e7490' },
      { key: 'pet_shop',     label: 'Pet Shops',     color: '#ea580c', stroke: '#c2410c' },
      { key: 'clothes',      label: 'Clothing',      color: '#7c3aed', stroke: '#6d28d9' },
      { key: 'electronics',  label: 'Electronics',   color: '#2563eb', stroke: '#1d4ed8' },
      { key: 'hardware',     label: 'Hardware',       color: '#78716c', stroke: '#57534e' },
      { key: 'shoes',        label: 'Shoes',          color: '#d97706', stroke: '#b45309' },
      { key: 'jewelry',      label: 'Jewelry',        color: '#e11d48', stroke: '#be123c' },
      { key: 'furniture',    label: 'Furniture',      color: '#92400e', stroke: '#78350f' },
      { key: 'mobile_phone', label: 'Phone Shops',    color: '#0891b2', stroke: '#0e7490' },
      { key: 'department_store', label: 'Dept. Stores',   color: '#7c3aed', stroke: '#6d28d9' },
      { key: 'sports_shop',     label: 'Sports Shops',    color: '#ea580c', stroke: '#c2410c' },
      { key: 'stationery',      label: 'Stationery',      color: '#2563eb', stroke: '#1d4ed8' },
      { key: 'gift_shop',       label: 'Gift Shops',      color: '#ec4899', stroke: '#db2777' },
      { key: 'tobacco',         label: 'Tobacco Shops',   color: '#78716c', stroke: '#57534e' },
      { key: 'newsagent',       label: 'Newsagents',      color: '#1d4ed8', stroke: '#1e40af' },
      { key: 'garden_centre',   label: 'Garden Centres',  color: '#16a34a', stroke: '#15803d' },
      { key: 'toy_shop',        label: 'Toy Shops',       color: '#f59e0b', stroke: '#d97706' },
      { key: 'alcohol_shop',    label: 'Alcohol Shops',   color: '#9f1239', stroke: '#881337' },
      { key: 'antiques',        label: 'Antiques',        color: '#92400e', stroke: '#78350f' },
      { key: 'cosmetics',       label: 'Cosmetics',       color: '#d946ef', stroke: '#a21caf' },
      { key: 'computer_shop',   label: 'Computer Shops',  color: '#2563eb', stroke: '#1d4ed8' },
      { key: 'greengrocer',     label: 'Greengrocers',    color: '#16a34a', stroke: '#15803d' },
      { key: 'confectionery',   label: 'Confectionery',   color: '#ec4899', stroke: '#db2777' },
      { key: 'art_shop',        label: 'Art Supplies',    color: '#e879f9', stroke: '#d946ef' },
    ],
  },
  {
    key: 'accommodation', label: 'Accommodation', icon: 'Bed',
    categories: [
      { key: 'hotel',    label: 'Hotels',    color: '#7c3aed', stroke: '#6d28d9' },
      { key: 'hostel',   label: 'Hostels',   color: '#2563eb', stroke: '#1d4ed8' },
      { key: 'campsite',    label: 'Campsites',    color: '#16a34a', stroke: '#15803d' },
      { key: 'apartment',   label: 'Apartments',   color: '#ea580c', stroke: '#c2410c' },
      { key: 'guest_house', label: 'Guest Houses', color: '#0891b2', stroke: '#0e7490' },
    ],
  },
  {
    key: 'culture', label: 'Arts & Culture', icon: 'Palette',
    categories: [
      { key: 'theatre',            label: 'Theatres',          color: '#0369a1', stroke: '#075985' },
      { key: 'arts_centre',        label: 'Arts Centres',      color: '#7c3aed', stroke: '#6d28d9' },
      { key: 'music_venue',        label: 'Music Venues',      color: '#b45309', stroke: '#78350f' },
      { key: 'community_centre',   label: 'Community Centres', color: '#15803d', stroke: '#14532d' },
      { key: 'outdoor_cinema',     label: 'Outdoor Cinemas',   color: '#0891b2', stroke: '#0e7490' },
    ],
  },
  {
    key: 'wellness', label: 'Wellness', icon: 'Heart',
    categories: [
      { key: 'sauna', label: 'Saunas', color: '#ea580c', stroke: '#c2410c' },
      { key: 'spa',   label: 'Spas',   color: '#0891b2', stroke: '#0e7490' },
    ],
  },
  {
    key: 'education', label: 'Education', icon: 'GraduationCap',
    categories: [
      { key: 'university',      label: 'Universities',    color: '#1d4ed8', stroke: '#1e40af' },
      { key: 'language_school',  label: 'Language Schools', color: '#059669', stroke: '#047857' },
      { key: 'kindergarten',     label: 'Kindergartens',   color: '#f59e0b', stroke: '#d97706' },
      { key: 'school',           label: 'Schools',         color: '#0891b2', stroke: '#0e7490' },
      { key: 'college',          label: 'Colleges',        color: '#0369a1', stroke: '#075985' },
      { key: 'driving_school',   label: 'Driving Schools', color: '#6b7280', stroke: '#4b5563' },
      { key: 'music_school',     label: 'Music Schools',   color: '#9333ea', stroke: '#7e22ce' },
    ],
  },
  {
    key: 'quirky', label: 'Weird & Wonderful', icon: 'Sparkles',
    categories: [
      { key: 'photo_booth',     label: 'Photo Booths',    color: '#7c3aed', stroke: '#6d28d9' },
      { key: 'public_bookcase', label: 'Book Exchanges',  color: '#0369a1', stroke: '#075985' },
      { key: 'drinking_water',  label: 'Water Fountains', color: '#0284c7', stroke: '#0369a1' },
      { key: 'public_piano',    label: 'Public Pianos',   color: '#e11d48', stroke: '#be123c' },
      { key: 'bbq_area',        label: 'BBQ Areas',       color: '#ea580c', stroke: '#c2410c' },
      { key: 'nudist_area',     label: 'FKK Areas',       color: '#d97706', stroke: '#b45309' },
      { key: 'defibrillator',   label: 'Defibrillators',  color: '#dc2626', stroke: '#b91c1c' },
      { key: 'spaeti',          label: 'Spätis',          color: '#f59e0b', stroke: '#d97706' },
      { key: 'tattoo',          label: 'Tattoo Shops',    color: '#6366f1', stroke: '#4f46e5' },
      { key: 'repair_cafe',     label: 'Repair Cafés',    color: '#15803d', stroke: '#14532d' },
      { key: 'mural',           label: 'Murals',          color: '#e879f9', stroke: '#d946ef' },
      { key: 'amusement_arcade',label: 'Arcades',         color: '#f59e0b', stroke: '#d97706' },
      { key: 'observatory',     label: 'Observatories',   color: '#1d4ed8', stroke: '#1e40af' },
      { key: 'clock_tower',     label: 'Clocks',          color: '#ca8a04', stroke: '#a16207' },
    ],
  },
  {
    key: 'health', label: 'Health', icon: 'HeartPulse',
    categories: [
      { key: 'physiotherapist',     label: 'Physiotherapy',      color: '#0891b2', stroke: '#0e7490' },
      { key: 'psychologist',        label: 'Psychologists',      color: '#7c3aed', stroke: '#6d28d9' },
      { key: 'midwife',             label: 'Midwives',           color: '#ec4899', stroke: '#db2777' },
      { key: 'speech_therapist',    label: 'Speech Therapy',     color: '#0284c7', stroke: '#0369a1' },
      { key: 'podiatrist',          label: 'Podiatrists',        color: '#059669', stroke: '#047857' },
      { key: 'alternative_medicine',label: 'Alternative Medicine',color: '#65a30d', stroke: '#4d7c0f' },
      { key: 'massage',             label: 'Massage',            color: '#d946ef', stroke: '#a21caf' },
      { key: 'hearing_aids',        label: 'Hearing Aids',       color: '#6b7280', stroke: '#4b5563' },
    ],
  },
  {
    key: 'craft', label: 'Trades & Craft', icon: 'Wrench',
    categories: [
      { key: 'locksmith',           label: 'Locksmiths',     color: '#78716c', stroke: '#57534e' },
      { key: 'electrician',         label: 'Electricians',   color: '#eab308', stroke: '#ca8a04' },
      { key: 'plumber',             label: 'Plumbers',       color: '#0284c7', stroke: '#0369a1' },
      { key: 'carpenter',           label: 'Carpenters',     color: '#92400e', stroke: '#78350f' },
      { key: 'painter_craft',       label: 'Painters',       color: '#e879f9', stroke: '#d946ef' },
      { key: 'photographer_studio', label: 'Photo Studios',  color: '#6366f1', stroke: '#4f46e5' },
      { key: 'printer',             label: 'Printers & Copy',color: '#4b5563', stroke: '#374151' },
      { key: 'tailor',              label: 'Tailors',        color: '#9f1239', stroke: '#881337' },
      { key: 'shoemaker',           label: 'Cobblers',       color: '#78716c', stroke: '#57534e' },
      { key: 'goldsmith',           label: 'Goldsmiths',     color: '#ca8a04', stroke: '#a16207' },
      { key: 'watchmaker',          label: 'Watchmakers',    color: '#525252', stroke: '#404040' },
      { key: 'glazier',             label: 'Glaziers',       color: '#0891b2', stroke: '#0e7490' },
      { key: 'key_cutter',          label: 'Key Cutters',    color: '#6b7280', stroke: '#4b5563' },
    ],
  },
]

// Lookup helpers
export function getPOIColor(group: string, category: string): { color: string; stroke: string } {
  const g = POI_GROUPS.find(g => g.key === group)
  const c = g?.categories.find(c => c.key === category)
  return c ? { color: c.color, stroke: c.stroke } : { color: '#6b7280', stroke: '#4b5563' }
}

export function getPOILabel(group: string, category: string): string {
  const g = POI_GROUPS.find(g => g.key === group)
  const c = g?.categories.find(c => c.key === category)
  return c?.label ?? category
}
